# MilkOutside Color Palette
set -l foreground e8e8e8
set -l selection 394b70
set -l comment 595959
set -l red fda1a0
set -l orange ffad00
set -l yellow ffad00
set -l green 92cf9c
set -l purple e79cfb
set -l cyan 63c3dd
set -l pink e79cfb

# Syntax Highlighting Colors
set -g fish_color_normal $foreground
set -g fish_color_command $cyan
set -g fish_color_keyword $pink
set -g fish_color_quote $yellow
set -g fish_color_redirection $foreground
set -g fish_color_end $orange
set -g fish_color_option $pink