#!/bin/sh
# Place file contents in ~/.config/sketchybar/sketchybarrc
# Make it executable: chmod +x ~/.config/sketchybar/sketchybarrc

# For more configuration details, see:
# https://felixkratz.github.io/SketchyBar/config/

###### BAR APPEARANCE #####
sketchybar --bar \
  height=40 \
  margin=10 \
  corner_radius=9 \
  blur_radius=30 \
  position=top \
  sticky=on \
  padding_right=10 \
  padding_left=10 \
  color=0x40303030 \
  border_width=2 \
  border_color=0xff585b70

###### DEFAULTS #####
sketchybar --default \
  icon.font="JetBrainsMono Nerd Font:Bold:16.0" \
  icon.color=0xffcdd6f4 \
  label.font="JetBrainsMono Nerd Font:Regular:14.0" \
  label.color=0xffcdd6f4 \
  padding_left=5 \
  padding_right=5 \
  label.padding_left=4 \
  label.padding_right=4 \
  icon.padding_left=4 \
  icon.padding_right=4

###### SPACE CONFIGURATION #####
SPACE_ICONS=("1" "2" "3" "4" "5" "6" "7" "8" "9" "10")

for i in "${!SPACE_ICONS[@]}"; do
  sid=$((i+1))
  sketchybar --add space space.$sid left \
             --set space.$sid associated_space=$sid \
                               icon=${SPACE_ICONS[i]} \
                               icon.font="JetBrainsMono Nerd Font:Bold:16.0" \
                               background.padding_left=5 \
                               background.padding_right=5 \
                               background.color=0x40404040 \
                               background.corner_radius=8 \
                               click_script="aerospace workspace $sid"
done

###### Aerospace workspace indicator #####
sketchybar --add item aerospace_workspace right \
           --set aerospace_workspace script="$PLUGIN_DIR/aerospace_workspace.sh" \
                                   icon.font="JetBrainsMono Nerd Font:Bold:16.0" \
                                   padding_left=10 \
                                   padding_right=10 \
                                   background.color=0xff45475a \
                                   background.corner_radius=8 \
                                   update_freq=2

###### CLOCK #####
sketchybar --add item clock right \
           --set clock update_freq=10 \
                       script="$PLUGIN_DIR/clock.sh" \
                       icon.color=0xffa6e3a1 \
                       label.color=0xffa6e3a1 \
                       padding_left=10 \
                       padding_right=10 \
                       background.color=0xff45475a \
                       background.corner_radius=8

###### WIFI #####
sketchybar --add item wifi right \
           --set wifi update_freq=5 \
                     script="$PLUGIN_DIR/wifi.sh" \
                     icon.color=0xff89b4fa \
                     label.color=0xffcdd6f4 \
                     padding_left=10 \
                     padding_right=10 \
                     background.color=0xff45475a \
                     background.corner_radius=8

###### BATTERY #####
sketchybar --add item battery right \
           --set battery update_freq=60 \
                     script="$PLUGIN_DIR/battery.sh" \
                     icon.color=0xfff9e2af \
                     label.color=0xffcdd6f4 \
                     padding_left=10 \
                     padding_right=10 \
                     background.color=0xff45475a \
                     background.corner_radius=8

###### VOLUME #####
sketchybar --add item volume right \
           --set volume script="$PLUGIN_DIR/volume.sh" \
                       icon.color=0xffeba0ac \
                       label.color=0xffcdd6f4 \
                       padding_left=10 \
                       padding_right=10 \
                       background.color=0xff45475a \
                       background.corner_radius=8 \
                       click_script="$PLUGIN_DIR/volume_click.sh"

###### FINALIZE CONFIG #####
sketchybar --update

echo "Sketchybar configuration loaded!"